{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "62ad08cf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "662dd70e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pygame 2.4.0 (SDL 2.26.4, Python 3.10.8)\n",
      "Hello from the pygame community. https://www.pygame.org/contribute.html\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Adithya\\anaconda3\\envs\\projects\\lib\\site-packages\\pydub\\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work\n",
      "  warn(\"Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work\", RuntimeWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "snoringds/full_test/0_108.wav\n",
      "snoringds/full_test/0_128.wav\n",
      "snoringds/full_test\\0_128.wav\n",
      "1/1 [==============================] - 0s 224ms/step\n",
      "snoringds/full_test/0_199.wav\n",
      "snoringds/full_test\\0_199.wav\n",
      "1/1 [==============================] - 0s 23ms/step\n",
      "snoringds/full_test/0_191.wav\n",
      "snoringds/full_test/F_16.wav\n",
      "snoringds/full_test/F_16.wav\n",
      "snoringds/full_test/F_16.wav\n",
      "snoringds/full_test/F_160.wav\n",
      "snoringds/full_test\\F_160.wav\n",
      "1/1 [==============================] - 0s 24ms/step\n",
      "snoringds/full_test/F_162.wav\n",
      "snoringds/full_test\\F_162.wav\n",
      "1/1 [==============================] - 0s 20ms/step\n",
      "snoringds/full_test/0_168.wav\n",
      "snoringds/full_test\\0_168.wav\n",
      "1/1 [==============================] - 0s 23ms/step\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "0",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Adithya\\anaconda3\\envs\\projects\\lib\\site-packages\\IPython\\core\\interactiveshell.py:3441: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import pygame\n",
    "\n",
    "from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import librosa.display\n",
    "import tensorflow as tf\n",
    "from keras.models import load_model\n",
    "from pydub import AudioSegment\n",
    "from playsound import playsound\n",
    "import os\n",
    "\n",
    "model = tf.keras.models.load_model('snoring_local.h5')\n",
    "global index\n",
    "global file_path\n",
    "\n",
    "folder_path = 'snoringds/full_test'\n",
    "file_list = os.listdir(folder_path)\n",
    "\n",
    "\n",
    "def preprocess_audio(file_path):\n",
    "    y, sr = librosa.load(file_path)\n",
    "    print(file_path)\n",
    "    spectrogram = librosa.feature.melspectrogram(y=y, sr=sr)\n",
    "    spectrogram = librosa.power_to_db(spectrogram, ref=np.max)\n",
    "    spectrogram = np.expand_dims(spectrogram, axis=-1)\n",
    "    return spectrogram\n",
    "\n",
    "\n",
    "class PlotViewer(QtWidgets.QMainWindow):\n",
    "    def __init__(self):\n",
    "        super(PlotViewer, self).__init__()\n",
    "        fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "\n",
    "        # Set the window dimensions\n",
    "        window_width = 800\n",
    "        window_height = 900\n",
    "        screen = QtWidgets.QApplication.primaryScreen()\n",
    "        self.setWindowIcon(QtGui.QIcon(\"medical-logo.jpg\"))\n",
    "        screen_rect = screen.availableGeometry()\n",
    "        window_x = int((screen_rect.width() - window_width) / 2)\n",
    "        window_y = int((screen_rect.height() - window_height) / 2)\n",
    "        self.setGeometry(window_x, window_y, window_width, window_height)\n",
    "\n",
    "        # Create the header label\n",
    "        header_label = QtWidgets.QLabel(\"Plot Viewer\", self)\n",
    "        header_label.setFont(QtGui.QFont(\"Arial\", 18))\n",
    "        header_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "        header_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "        header_label.setGeometry(10, 10, window_width - 20, 30)\n",
    "\n",
    "        # Create the input space\n",
    "        input_frame = QtWidgets.QFrame(self)\n",
    "        input_frame.setStyleSheet(\"background-color: #3533CD;\")\n",
    "        input_frame.setGeometry(60, 40, 700, 270)\n",
    "\n",
    "        input_label = QtWidgets.QLabel(\"Enter Index:\", input_frame)\n",
    "        input_label.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        input_label.setStyleSheet(\"background-color: #3533CD; color: white;\")  # Set font color to white\n",
    "        input_label.setGeometry(220, 20, 100, 50)  # Adjust the position of the input label\n",
    "\n",
    "        self.input_space = QtWidgets.QLineEdit(input_frame)\n",
    "        self.input_space.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        self.input_space.setGeometry(340, 30, 100, 30)\n",
    "        self.input_space.setStyleSheet(\"background-color: #3533CD; color: white;\") \n",
    "\n",
    "        # Create the button frame\n",
    "        button_frame = QtWidgets.QFrame(self)\n",
    "        button_frame.setStyleSheet(\"background-color:#3533CD;\")\n",
    "        button_frame.setGeometry(int((window_width - 560) / 2), 100, 560, 600)\n",
    "\n",
    "        button_spacing = 70\n",
    "        button_size = 50\n",
    "        button_margin = int((500 - (button_spacing * 4 + button_size)) / 2)\n",
    "\n",
    "        play_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        play_button.setIcon(QtGui.QIcon(\"play.png\"))\n",
    "        play_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        play_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        play_button.setGeometry(button_margin, 20, button_size, button_size)\n",
    "        play_button.clicked.connect(self.play_audio)\n",
    "\n",
    "        plot_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        plot_button.setIcon(QtGui.QIcon(\"plotf.png\"))\n",
    "        plot_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        plot_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        plot_button.setGeometry(button_margin + button_spacing, 20, button_size, button_size)\n",
    "        plot_button.clicked.connect(self.plot_graph)\n",
    "\n",
    "        spec = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        spec.setIcon(QtGui.QIcon(\"spec.png\"))\n",
    "        spec.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        spec.setStyleSheet(\"background-color: transparent;\")\n",
    "        spec.setGeometry(button_margin + button_spacing * 2, 20, button_size, button_size)\n",
    "        spec.clicked.connect(self.show_spectrogram)\n",
    "\n",
    "        save_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        save_button.setIcon(QtGui.QIcon(\"brain.png\"))\n",
    "        save_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        save_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        save_button.setGeometry(button_margin + button_spacing * 3, 20, button_size, button_size)\n",
    "        save_button.clicked.connect(self.save_plot)\n",
    "\n",
    "        refresh_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        refresh_button.setIcon(QtGui.QIcon(\"bv.png\"))\n",
    "        refresh_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        refresh_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        refresh_button.setGeometry(button_margin + button_spacing * 4, 20, button_size, button_size)\n",
    "        refresh_button.clicked.connect(self.refresh)\n",
    "        self.index = 0\n",
    "\n",
    "        # ... Existing code ...\n",
    "\n",
    "        # Create the subtract button\n",
    "        subtract_button = QtWidgets.QPushButton(\"-\", input_frame)\n",
    "        subtract_button.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        subtract_button.setStyleSheet(\"background-color: #3533CD; color: white;\")\n",
    "        subtract_button.setGeometry(450, 30, 30, 30)\n",
    "        subtract_button.clicked.connect(self.subtract_index)\n",
    "\n",
    "        # Create the add button\n",
    "        add_button = QtWidgets.QPushButton(\"+\", input_frame)\n",
    "        add_button.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        add_button.setStyleSheet(\"background-color: #3533CD; color: white;\")  # Set font color to white\n",
    "        add_button.setGeometry(480, 30, 30, 30)\n",
    "        add_button.clicked.connect(self.add_index)\n",
    "\n",
    "        exit_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        exit_button.setIcon(QtGui.QIcon(\"exit.png\"))\n",
    "        exit_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        exit_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        exit_button.setGeometry(button_margin + button_spacing * 5, 20, button_size, button_size)\n",
    "        exit_button.clicked.connect(self.exit_application)\n",
    "\n",
    "        # Create the plot space\n",
    "        self.plot_space = QtWidgets.QWidget(self)\n",
    "        self.plot_space.setStyleSheet(\"background-color:#3533CD\")\n",
    "        self.plot_space.setGeometry(10, 250, window_width - 20, 400)\n",
    "\n",
    "        # Create the beat label\n",
    "        self.beat_label = QtWidgets.QLabel(self)\n",
    "        self.beat_label.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        self.beat_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "        self.beat_label.setGeometry(int((window_width -700) / 2), 660, window_width - 100, 30)\n",
    "\n",
    "        # Create the footer label\n",
    "        footer_label = QtWidgets.QLabel(\"© 2023 AWAKE Plot Viewer. All rights reserved.\", self)\n",
    "        footer_label.setFont(QtGui.QFont(\"Arial\", 10))\n",
    "        footer_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "        footer_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "        footer_label.setGeometry(10, 790, window_width - 20, 20)\n",
    "\n",
    "        plot = fig.add_subplot(111)\n",
    "        plot.plot(0, 0)\n",
    "        plot.set_xlabel('X', color='white')  # Set X-axis label color to white\n",
    "        plot.set_ylabel('Y', color='white')  # Set Y-axis label color to white\n",
    "        plot.set_title('Plot', color='white')  # Set title color to white\n",
    "\n",
    "        # Set tick color and tick label color to white\n",
    "        plot.tick_params(colors='white')\n",
    "        plot.xaxis.label.set_color('white')\n",
    "        plot.yaxis.label.set_color('white')\n",
    "\n",
    "         \n",
    "        canvas = FigureCanvas(fig)\n",
    "        canvas.setGeometry(0, 0, 780, 400)\n",
    "        canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "        canvas.setParent(self.plot_space)\n",
    "\n",
    "        self.setWindowTitle(\"Plot Viewer\")\n",
    "        self.setStyleSheet(\"background-color:#3533CD;\")\n",
    "\n",
    "    def refresh(self):\n",
    "        for child in self.plot_space.children():\n",
    "            child.deleteLater()\n",
    "        self.input_space.clear()\n",
    "        self.beat_label.setText(\"\")\n",
    "        \n",
    "    def add_index(self):\n",
    "        index_text = self.input_space.text()\n",
    "        if index_text:\n",
    "            self.index = int(index_text) + 1\n",
    "            self.input_space.setText(str(self.index))\n",
    "\n",
    "    def subtract_index(self):\n",
    "        index_text = self.input_space.text()\n",
    "        if index_text and int(index_text) > 0:\n",
    "            self.index = int(index_text) - 1\n",
    "            self.input_space.setText(str(self.index))\n",
    "\n",
    "    def plot_graph(self):\n",
    "        for child in self.plot_space.children():\n",
    "            child.deleteLater()\n",
    "\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        if 0 <= index < len(file_list):\n",
    "            file_name = file_list[index]\n",
    "            file_path = os.path.join(folder_path, file_name)\n",
    "            audio, sr = librosa.load(file_path)\n",
    "            fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "            plot = fig.add_subplot(111)\n",
    "            plot.plot(audio)\n",
    "            plot.set_xlabel('X', color='white')  # Set X-axis label color to white\n",
    "            plot.set_ylabel('Y', color='white')  # Set Y-axis label color to white\n",
    "            plot.set_title('Plot', color='white')  # Set title color to white\n",
    "\n",
    "            # Set tick color and tick label color to white\n",
    "            plot.tick_params(colors='white')\n",
    "            plot.xaxis.label.set_color('white')\n",
    "            plot.yaxis.label.set_color('white')\n",
    "\n",
    "            # Set the color of the frame and the spines to white\n",
    "            plot.spines['top'].set_color('white')\n",
    "            plot.spines['bottom'].set_color('white')\n",
    "            plot.spines['left'].set_color('white')\n",
    "            plot.spines['right'].set_color('white')\n",
    "\n",
    "            canvas = FigureCanvas(fig)\n",
    "            canvas.setGeometry(0, 0, 780, 400)\n",
    "            canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "            canvas.setParent(self.plot_space)\n",
    "            canvas.show()\n",
    "\n",
    "\n",
    "    def save_plot(self):\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        if 0 <= index < len(file_list):\n",
    "            file_name = file_list[index]\n",
    "            file_path = os.path.join(folder_path, file_name)\n",
    "            new_spectrogram = preprocess_audio(file_path)\n",
    "            prediction = model.predict(np.array([new_spectrogram]))\n",
    "            if prediction[0][0] > 0.1:\n",
    "                prediction_text = 'The audio file contains snoring.'\n",
    "            else:\n",
    "                prediction_text = 'The audio file does not contain snoring.'\n",
    "\n",
    "            self.beat_label.setText(prediction_text)\n",
    "            self.beat_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "            self.beat_label.setStyleSheet(\"background-color: black; color: white;\")\n",
    "\n",
    "\n",
    "    def play_audio(self):\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        if 0 <= index < len(file_list):\n",
    "            file_name = file_list[index]\n",
    "            file_path = os.path.join(folder_path, file_name)\n",
    "            string_with_backslashes = file_path\n",
    "            string_with_forwardslashes = string_with_backslashes.replace('\\\\', '/')\n",
    "            print(string_with_forwardslashes)\n",
    "\n",
    "            #playsound(string_with_forwardslashes, alias='my_audio_alias')\n",
    "            pygame.mixer.init()\n",
    "            pygame.mixer.music.load(string_with_forwardslashes)\n",
    "            pygame.mixer.music.play()\n",
    "\n",
    "    def show_spectrogram(self):\n",
    "        for child in self.plot_space.children():\n",
    "            child.deleteLater()\n",
    "\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        if 0 <= index < len(file_list):\n",
    "            file_name = file_list[index]\n",
    "            file_path = os.path.join(folder_path, file_name)\n",
    "            audio, sr = librosa.load(file_path)\n",
    "            spectrogram = librosa.feature.melspectrogram(y=audio, sr=sr)\n",
    "            fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "            plot = fig.add_subplot(111)\n",
    "            img = librosa.display.specshow(librosa.power_to_db(spectrogram, ref=np.max), x_axis='time', y_axis='mel',\n",
    "                                           sr=sr, ax=plot)\n",
    "            fig.colorbar(img, ax=plot, format='%+2.0f dB')\n",
    "\n",
    "            # Set axis label color and font color to white\n",
    "            plot.set_title('Spectrogram', color='white')\n",
    "            plot.set_xlabel('Time', color='white')\n",
    "            plot.set_ylabel('Frequency', color='white')\n",
    "\n",
    "            # Set tick color and tick label color to white\n",
    "            plot.tick_params(colors='white')\n",
    "            plot.xaxis.label.set_color('white')\n",
    "            plot.yaxis.label.set_color('white')\n",
    "\n",
    "            # Set the color of the frame and the spines to white\n",
    "            plot.spines['top'].set_color('white')\n",
    "            plot.spines['bottom'].set_color('white')\n",
    "            plot.spines['left'].set_color('white')\n",
    "            plot.spines['right'].set_color('white')\n",
    "\n",
    "            canvas = FigureCanvas(fig)\n",
    "            canvas.setGeometry(0, 0, 780, 400)\n",
    "            canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "            canvas.setParent(self.plot_space)\n",
    "            canvas.show()\n",
    "\n",
    "\n",
    "    def exit_application(self):\n",
    "        sys.exit()\n",
    "\n",
    "\n",
    "app = QtWidgets.QApplication(sys.argv)\n",
    "viewer = PlotViewer()\n",
    "\n",
    "viewer.show()\n",
    "sys.exit(app.exec_())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a702c3fc",
   "metadata": {},
   "source": [
    "# !pip install pygame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6409acb5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "\n",
    "\n",
    "from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import librosa.display\n",
    "import tensorflow as tf\n",
    "from keras.models import load_model\n",
    "from pydub import AudioSegment\n",
    "from playsound import playsound\n",
    "import os\n",
    "\n",
    "model = tf.keras.models.load_model('best_model.h5')\n",
    "global index\n",
    "global file_path\n",
    "\n",
    " \n",
    "test_df = pd.read_csv('mitbih_test.csv', header=None)\n",
    "\n",
    "def preprocess_audio(file_path):\n",
    "    y, sr = librosa.load(file_path)\n",
    "    print(file_path)\n",
    "    spectrogram = librosa.feature.melspectrogram(y=y, sr=sr)\n",
    "    spectrogram = librosa.power_to_db(spectrogram, ref=np.max)\n",
    "    spectrogram = np.expand_dims(spectrogram, axis=-1)\n",
    "    return spectrogram\n",
    "\n",
    "\n",
    "class PlotViewer(QtWidgets.QMainWindow):\n",
    "    def __init__(self):\n",
    "        super(PlotViewer, self).__init__()\n",
    "        fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "\n",
    "        # Set the window dimensions\n",
    "        window_width = 800\n",
    "        window_height = 900\n",
    "        screen = QtWidgets.QApplication.primaryScreen()\n",
    "        self.setWindowIcon(QtGui.QIcon(\"medical-logo.jpg\"))\n",
    "        screen_rect = screen.availableGeometry()\n",
    "        window_x = int((screen_rect.width() - window_width) / 2)\n",
    "        window_y = int((screen_rect.height() - window_height) / 2)\n",
    "        self.setGeometry(window_x, window_y, window_width, window_height)\n",
    "\n",
    "        # Create the header label\n",
    "        header_label = QtWidgets.QLabel(\"Plot Viewer\", self)\n",
    "        header_label.setFont(QtGui.QFont(\"Arial\", 18))\n",
    "        header_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "        header_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "        header_label.setGeometry(10, 10, window_width - 20, 30)\n",
    "\n",
    "        # Create the input space\n",
    "        input_frame = QtWidgets.QFrame(self)\n",
    "        input_frame.setStyleSheet(\"background-color: #3533CD;\")\n",
    "        input_frame.setGeometry(60, 40, 700, 270)\n",
    "\n",
    "        input_label = QtWidgets.QLabel(\"Enter Index:\", input_frame)\n",
    "        input_label.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        input_label.setStyleSheet(\"background-color: #3533CD; color: white;\")  # Set font color to white\n",
    "        input_label.setGeometry(220, 20, 100, 50)  # Adjust the position of the input label\n",
    "\n",
    "        self.input_space = QtWidgets.QLineEdit(input_frame)\n",
    "        self.input_space.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        self.input_space.setGeometry(340, 30, 100, 30)\n",
    "        self.input_space.setStyleSheet(\"background-color: #3533CD; color: white;\") \n",
    "\n",
    "        # Create the button frame\n",
    "        button_frame = QtWidgets.QFrame(self)\n",
    "        button_frame.setStyleSheet(\"background-color:#3533CD;\")\n",
    "        button_frame.setGeometry(int((window_width - 560) / 2), 100, 560, 600)\n",
    "\n",
    "        button_spacing = 70\n",
    "        button_size = 50\n",
    "        button_margin = int((500 - (button_spacing * 4 + button_size)) / 2)\n",
    "\n",
    "        \n",
    "\n",
    "        plot_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        plot_button.setIcon(QtGui.QIcon(\"plotf.png\"))\n",
    "        plot_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        plot_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        plot_button.setGeometry(button_margin + button_spacing, 20, button_size, button_size)\n",
    "        plot_button.clicked.connect(self.plot_graph)\n",
    "\n",
    "        spec = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        spec.setIcon(QtGui.QIcon(\"spec.png\"))\n",
    "        spec.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        spec.setStyleSheet(\"background-color: transparent;\")\n",
    "        spec.setGeometry(button_margin + button_spacing * 2, 20, button_size, button_size)\n",
    "        spec.clicked.connect(self.show_spectrogram)\n",
    "\n",
    "        save_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        save_button.setIcon(QtGui.QIcon(\"brain.png\"))\n",
    "        save_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        save_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        save_button.setGeometry(button_margin + button_spacing * 3, 20, button_size, button_size)\n",
    "        save_button.clicked.connect(self.save_plot)\n",
    "\n",
    "        refresh_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        refresh_button.setIcon(QtGui.QIcon(\"bv.png\"))\n",
    "        refresh_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        refresh_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        refresh_button.setGeometry(button_margin + button_spacing * 4, 20, button_size, button_size)\n",
    "        refresh_button.clicked.connect(self.refresh)\n",
    "        self.index = 0\n",
    "\n",
    "        # ... Existing code ...\n",
    "\n",
    "        # Create the subtract button\n",
    "        subtract_button = QtWidgets.QPushButton(\"-\", input_frame)\n",
    "        subtract_button.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        subtract_button.setStyleSheet(\"background-color: #3533CD; color: white;\")\n",
    "        subtract_button.setGeometry(450, 30, 30, 30)\n",
    "        subtract_button.clicked.connect(self.subtract_index)\n",
    "\n",
    "        # Create the add button\n",
    "        add_button = QtWidgets.QPushButton(\"+\", input_frame)\n",
    "        add_button.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        add_button.setStyleSheet(\"background-color: #3533CD; color: white;\")  # Set font color to white\n",
    "        add_button.setGeometry(480, 30, 30, 30)\n",
    "        add_button.clicked.connect(self.add_index)\n",
    "\n",
    "        exit_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "        exit_button.setIcon(QtGui.QIcon(\"exit.png\"))\n",
    "        exit_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "        exit_button.setStyleSheet(\"background-color: transparent;\")\n",
    "        exit_button.setGeometry(button_margin + button_spacing * 5, 20, button_size, button_size)\n",
    "        exit_button.clicked.connect(self.exit_application)\n",
    "\n",
    "        # Create the plot space\n",
    "        self.plot_space = QtWidgets.QWidget(self)\n",
    "        self.plot_space.setStyleSheet(\"background-color:#3533CD\")\n",
    "        self.plot_space.setGeometry(10, 250, window_width - 20, 400)\n",
    "\n",
    "        # Create the beat label\n",
    "        self.beat_label = QtWidgets.QLabel(self)\n",
    "        self.beat_label.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "        self.beat_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "        self.beat_label.setGeometry(int((window_width -700) / 2), 660, window_width - 100, 30)\n",
    "\n",
    "        # Create the footer label\n",
    "        footer_label = QtWidgets.QLabel(\"© 2023 AWAKE Plot Viewer. All rights reserved.\", self)\n",
    "        footer_label.setFont(QtGui.QFont(\"Arial\", 10))\n",
    "        footer_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "        footer_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "        footer_label.setGeometry(10, 790, window_width - 20, 20)\n",
    "\n",
    "        plot = fig.add_subplot(111)\n",
    "        plot.plot(0, 0)\n",
    "        plot.set_xlabel('X', color='white')  # Set X-axis label color to white\n",
    "        plot.set_ylabel('Y', color='white')  # Set Y-axis label color to white\n",
    "        plot.set_title('Plot', color='white')  # Set title color to white\n",
    "\n",
    "        # Set tick color and tick label color to white\n",
    "        plot.tick_params(colors='white')\n",
    "        plot.xaxis.label.set_color('white')\n",
    "        plot.yaxis.label.set_color('white')\n",
    "\n",
    "         \n",
    "        canvas = FigureCanvas(fig)\n",
    "        canvas.setGeometry(0, 0, 780, 400)\n",
    "        canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "        canvas.setParent(self.plot_space)\n",
    "\n",
    "        self.setWindowTitle(\"Plot Viewer\")\n",
    "        self.setStyleSheet(\"background-color:#3533CD;\")\n",
    "\n",
    "    def refresh(self):\n",
    "        for child in self.plot_space.children():\n",
    "            child.deleteLater()\n",
    "        self.input_space.clear()\n",
    "        self.beat_label.setText(\"\")\n",
    "        \n",
    "    def add_index(self):\n",
    "        index_text = self.input_space.text()\n",
    "        if index_text:\n",
    "            self.index = int(index_text) + 1\n",
    "            self.input_space.setText(str(self.index))\n",
    "\n",
    "    def subtract_index(self):\n",
    "        index_text = self.input_space.text()\n",
    "        if index_text and int(index_text) > 0:\n",
    "            self.index = int(index_text) - 1\n",
    "            self.input_space.setText(str(self.index))\n",
    "\n",
    "    def plot_graph(self):\n",
    "        for child in self.plot_space.children():\n",
    "            child.deleteLater()\n",
    "\n",
    "        index = int(self.input_space.text())\n",
    "        fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "        plot = fig.add_subplot(111)\n",
    "        plot.plot(test_df.iloc[index].values)\n",
    "        plot.set_xlabel('X', color='white')  # Set X-axis label color to white\n",
    "        plot.set_ylabel('Y', color='white')  # Set Y-axis label color to white\n",
    "        plot.set_title('Plot', color='white')  # Set title color to white\n",
    "\n",
    "        # Set tick color and tick label color to white\n",
    "        plot.tick_params(colors='white')\n",
    "        plot.xaxis.label.set_color('white')\n",
    "        plot.yaxis.label.set_color('white')\n",
    "\n",
    "        # Set the color of the frame and the spines to white\n",
    "        plot.spines['top'].set_color('white')\n",
    "        plot.spines['bottom'].set_color('white')\n",
    "        plot.spines['left'].set_color('white')\n",
    "        plot.spines['right'].set_color('white')\n",
    "\n",
    "        canvas = FigureCanvas(fig)\n",
    "        canvas.setGeometry(0, 0, 780, 400)\n",
    "        canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "        canvas.setParent(self.plot_space)\n",
    "        canvas.show()\n",
    "\n",
    "      \n",
    "\n",
    "    # Retrieve the array element from test_df based on the input index\n",
    "     \n",
    "\n",
    "\n",
    "     \n",
    "            \n",
    "\n",
    "\n",
    "    def save_plot(self):\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        x_array = test_df.iloc[index].values\n",
    "        x_reshaped = x_array[:186].reshape(-1, 186, 1)\n",
    "        y_predict = model.predict(x_reshaped)\n",
    "        y_pred_inv = np.argmax(y_predict, axis=1)\n",
    "\n",
    "        if 0 in y_pred_inv:\n",
    "            beat_type = \"Non-ectopic beats detected\"\n",
    "        elif 1 in y_pred_inv:\n",
    "            beat_type = \"Supraventricular ectopic beats detected\"\n",
    "        elif 2 in y_pred_inv:\n",
    "            beat_type = \"Ventricular ectopic beats detected\"\n",
    "        elif 3 in y_pred_inv:\n",
    "            beat_type = \"Fusion Beats detected\"\n",
    "        elif 4 in y_pred_inv:\n",
    "            beat_type = \"Unknown Beats detected\"\n",
    "        else:\n",
    "            beat_type = \"Beat type not detected\"\n",
    "        self.beat_label.setText(beat_type)\n",
    "        self.beat_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "        self.beat_label.setStyleSheet(\"background-color: black; color: white;\")\n",
    "\n",
    "\n",
    "    def play_audio(self):\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        if 0 <= index < len(file_list):\n",
    "            file_name = file_list[index]\n",
    "            file_path = os.path.join(folder_path, file_name)\n",
    "            string_with_backslashes = file_path\n",
    "            string_with_forwardslashes = string_with_backslashes.replace('\\\\', '/')\n",
    "            print(string_with_forwardslashes)\n",
    "\n",
    "            #playsound(string_with_forwardslashes, alias='my_audio_alias')\n",
    "            pygame.mixer.init()\n",
    "            pygame.mixer.music.load(string_with_forwardslashes)\n",
    "            pygame.mixer.music.play()\n",
    "\n",
    "   \n",
    "    def show_spectrogram(self):\n",
    "        class_number=0\n",
    "        size=70\n",
    "        min_=5\n",
    "        bins=65\n",
    "        for child in self.plot_space.children():\n",
    "            child.deleteLater()\n",
    "            \n",
    "            \n",
    "\n",
    "        \n",
    "\n",
    "        index = int(self.input_space.text())\n",
    "\n",
    "        img = test_df.iloc[20000].values\n",
    "        \n",
    "        \n",
    "        ###\n",
    "        img=test_df.loc[test_df[187]==class_number].values\n",
    "        img=img[:,min_:size]\n",
    "        img_flatten=img.flatten()\n",
    "\n",
    "        final1=np.arange(min_,size)\n",
    "        for i in range (img.shape[0]-1):\n",
    "            tempo1=np.arange(min_,size)\n",
    "            final1=np.concatenate((final1, tempo1), axis=None)\n",
    "     \n",
    "        img=plt.hist(final1,img_flatten, cmap=plt.cm.jet)\n",
    "        plt.show()\n",
    "    \n",
    " \n",
    "\n",
    "        \"\"\"spectrogram = librosa.feature.melspectrogram(y=img, sr=0.1, n_fft=100, hop_length=256)\n",
    "        fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "        plot = fig.add_subplot(111)\n",
    "        img = librosa.display.specshow(spectrogram,  x_axis='time', y_axis='mel',\n",
    "                                       sr=0.1, ax=plot)\"\"\"\n",
    "        fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "        plot = fig.add_subplot(111)\n",
    " \n",
    "        # Set axis label color and font color to white\n",
    "        plot.set_title('Spectrogram', color='white')\n",
    "        plot.set_xlabel('Time', color='white')\n",
    "        plot.set_ylabel('Frequency', color='white')\n",
    "\n",
    "        # Set tick color and tick label color to white\n",
    "        plot.tick_params(colors='white')\n",
    "        plot.xaxis.label.set_color('white')\n",
    "        plot.yaxis.label.set_color('white')\n",
    "\n",
    "        # Set the color of the frame and the spines to white\n",
    "        plot.spines['top'].set_color('white')\n",
    "        plot.spines['bottom'].set_color('white')\n",
    "        plot.spines['left'].set_color('white')\n",
    "        plot.spines['right'].set_color('white')\n",
    "\n",
    "        canvas = FigureCanvas(img)\n",
    "        canvas.setGeometry(0, 0, 780, 400)\n",
    "        canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "        canvas.setParent(self.plot_space)\n",
    "        canvas.show()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    def exit_application(self):\n",
    "        sys.exit()\n",
    "\n",
    "\n",
    "app = QtWidgets.QApplication(sys.argv)\n",
    "viewer = PlotViewer()\n",
    "\n",
    "\n",
    "viewer.show()\n",
    "sys.exit(app.exec_())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1361cf02",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QVBoxLayout, QWidget\n",
    "\n",
    "class CodeWindow(QMainWindow):\n",
    "    def __init__(self, code):\n",
    "        super().__init__()\n",
    "        self.setWindowTitle(\"Code Window\")\n",
    "        self.setGeometry(100, 100, 400, 300)\n",
    "        \n",
    "        self.code = code\n",
    "\n",
    "    def run_code(self):\n",
    "        exec(self.code)\n",
    "\n",
    "class MenuWindow(QMainWindow):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.setWindowTitle(\"Menu Window\")\n",
    "        self.setGeometry(100, 100, 200, 150)\n",
    "        \n",
    "        layout = QVBoxLayout()\n",
    "        widget = QWidget()\n",
    "        widget.setLayout(layout)\n",
    "        self.setCentralWidget(widget)\n",
    "        \n",
    "        button1 = QPushButton(\"Code 1\", self)\n",
    "        button1.clicked.connect(self.open_code_window1)\n",
    "        layout.addWidget(button1)\n",
    "\n",
    "        button2 = QPushButton(\"Code 2\", self)\n",
    "        button2.clicked.connect(self.open_code_window2)\n",
    "        layout.addWidget(button2)\n",
    "        \n",
    "    def open_code_window1(self):\n",
    "        code = \"\"\"\n",
    "print(\"This is Code 1\")\n",
    "\"\"\"\n",
    "        code_window = CodeWindow(code)\n",
    "        code_window.show()\n",
    "\n",
    "    def open_code_window2(self):\n",
    "        code = \"\"\"\n",
    "print(\"This is Code 2\")\n",
    "\"\"\"\n",
    "        code_window = CodeWindow(code)\n",
    "        code_window.show()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app = QApplication(sys.argv)\n",
    "    menu_window = MenuWindow()\n",
    "    menu_window.show()\n",
    "    sys.exit(app.exec_())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c90bf261",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QVBoxLayout, QWidget, QMessageBox\n",
    "\n",
    "class CodeWindow(QMainWindow):\n",
    "    def __init__(self, code):\n",
    "        super().__init__()\n",
    "        self.setWindowTitle(\"Code Window\")\n",
    "        self.setGeometry(100, 100, 400, 300)\n",
    "        \n",
    "        self.code = code\n",
    "\n",
    "    def run_code(self):\n",
    "        try:\n",
    "            exec(self.code)\n",
    "        except Exception as e:\n",
    "            QMessageBox.critical(self, \"Error\", str(e))\n",
    "\n",
    "class MenuWindow(QMainWindow):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.setWindowTitle(\"Menu Window\")\n",
    "        self.setGeometry(100, 100, 200, 150)\n",
    "        \n",
    "        layout = QVBoxLayout()\n",
    "        widget = QWidget()\n",
    "        widget.setLayout(layout)\n",
    "        self.setCentralWidget(widget)\n",
    "        \n",
    "        button1 = QPushButton(\"Code 1\", self)\n",
    "        button1.clicked.connect(self.open_code_window1)\n",
    "        layout.addWidget(button1)\n",
    "\n",
    "        button2 = QPushButton(\"Code 2\", self)\n",
    "        button2.clicked.connect(self.open_code_window2)\n",
    "        layout.addWidget(button2)\n",
    "        \n",
    "    def open_code_window1(self):\n",
    "        code = \"\"\"\n",
    "print(\"This is Code 1\")\n",
    "\"\"\"\n",
    "        code_window = CodeWindow(code)\n",
    "        code_window.show()\n",
    "        code_window.run_code()\n",
    "\n",
    "    def open_code_window2(self):\n",
    "        import sys\n",
    "\n",
    "\n",
    "        from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "        from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas\n",
    "        import matplotlib.pyplot as plt\n",
    "        import pandas as pd\n",
    "        import numpy as np\n",
    "        import librosa.display\n",
    "        import tensorflow as tf\n",
    "        from keras.models import load_model\n",
    "        from pydub import AudioSegment\n",
    "        from playsound import playsound\n",
    "        import os\n",
    "\n",
    "        model = tf.keras.models.load_model('best_model.h5')\n",
    "        global index\n",
    "        global file_path\n",
    "\n",
    "\n",
    "        test_df = pd.read_csv('mitbih_test.csv', header=None)\n",
    "\n",
    "        def preprocess_audio(file_path):\n",
    "            y, sr = librosa.load(file_path)\n",
    "            print(file_path)\n",
    "            spectrogram = librosa.feature.melspectrogram(y=y, sr=sr)\n",
    "            spectrogram = librosa.power_to_db(spectrogram, ref=np.max)\n",
    "            spectrogram = np.expand_dims(spectrogram, axis=-1)\n",
    "            return spectrogram\n",
    "\n",
    "\n",
    "        class PlotViewer(QtWidgets.QMainWindow):\n",
    "            def __init__(self):\n",
    "                super(PlotViewer, self).__init__()\n",
    "                fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "\n",
    "                # Set the window dimensions\n",
    "                window_width = 800\n",
    "                window_height = 900\n",
    "                screen = QtWidgets.QApplication.primaryScreen()\n",
    "                self.setWindowIcon(QtGui.QIcon(\"medical-logo.jpg\"))\n",
    "                screen_rect = screen.availableGeometry()\n",
    "                window_x = int((screen_rect.width() - window_width) / 2)\n",
    "                window_y = int((screen_rect.height() - window_height) / 2)\n",
    "                self.setGeometry(window_x, window_y, window_width, window_height)\n",
    "\n",
    "                # Create the header label\n",
    "                header_label = QtWidgets.QLabel(\"Plot Viewer\", self)\n",
    "                header_label.setFont(QtGui.QFont(\"Arial\", 18))\n",
    "                header_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "                header_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "                header_label.setGeometry(10, 10, window_width - 20, 30)\n",
    "\n",
    "                # Create the input space\n",
    "                input_frame = QtWidgets.QFrame(self)\n",
    "                input_frame.setStyleSheet(\"background-color: #3533CD;\")\n",
    "                input_frame.setGeometry(60, 40, 700, 270)\n",
    "\n",
    "                input_label = QtWidgets.QLabel(\"Enter Index:\", input_frame)\n",
    "                input_label.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "                input_label.setStyleSheet(\"background-color: #3533CD; color: white;\")  # Set font color to white\n",
    "                input_label.setGeometry(220, 20, 100, 50)  # Adjust the position of the input label\n",
    "\n",
    "                self.input_space = QtWidgets.QLineEdit(input_frame)\n",
    "                self.input_space.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "                self.input_space.setGeometry(340, 30, 100, 30)\n",
    "                self.input_space.setStyleSheet(\"background-color: #3533CD; color: white;\") \n",
    "\n",
    "                # Create the button frame\n",
    "                button_frame = QtWidgets.QFrame(self)\n",
    "                button_frame.setStyleSheet(\"background-color:#3533CD;\")\n",
    "                button_frame.setGeometry(int((window_width - 560) / 2), 100, 560, 600)\n",
    "\n",
    "                button_spacing = 70\n",
    "                button_size = 50\n",
    "                button_margin = int((500 - (button_spacing * 4 + button_size)) / 2)\n",
    "\n",
    "\n",
    "\n",
    "                plot_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "                plot_button.setIcon(QtGui.QIcon(\"plotf.png\"))\n",
    "                plot_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "                plot_button.setStyleSheet(\"background-color: transparent;\")\n",
    "                plot_button.setGeometry(button_margin + button_spacing, 20, button_size, button_size)\n",
    "                plot_button.clicked.connect(self.plot_graph)\n",
    "\n",
    "                spec = QtWidgets.QPushButton(\"\", button_frame)\n",
    "                spec.setIcon(QtGui.QIcon(\"spec.png\"))\n",
    "                spec.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "                spec.setStyleSheet(\"background-color: transparent;\")\n",
    "                spec.setGeometry(button_margin + button_spacing * 2, 20, button_size, button_size)\n",
    "                spec.clicked.connect(self.show_spectrogram)\n",
    "\n",
    "                save_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "                save_button.setIcon(QtGui.QIcon(\"brain.png\"))\n",
    "                save_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "                save_button.setStyleSheet(\"background-color: transparent;\")\n",
    "                save_button.setGeometry(button_margin + button_spacing * 3, 20, button_size, button_size)\n",
    "                save_button.clicked.connect(self.save_plot)\n",
    "\n",
    "                refresh_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "                refresh_button.setIcon(QtGui.QIcon(\"bv.png\"))\n",
    "                refresh_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "                refresh_button.setStyleSheet(\"background-color: transparent;\")\n",
    "                refresh_button.setGeometry(button_margin + button_spacing * 4, 20, button_size, button_size)\n",
    "                refresh_button.clicked.connect(self.refresh)\n",
    "                self.index = 0\n",
    "\n",
    "                # ... Existing code ...\n",
    "\n",
    "                # Create the subtract button\n",
    "                subtract_button = QtWidgets.QPushButton(\"-\", input_frame)\n",
    "                subtract_button.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "                subtract_button.setStyleSheet(\"background-color: #3533CD; color: white;\")\n",
    "                subtract_button.setGeometry(450, 30, 30, 30)\n",
    "                subtract_button.clicked.connect(self.subtract_index)\n",
    "\n",
    "                # Create the add button\n",
    "                add_button = QtWidgets.QPushButton(\"+\", input_frame)\n",
    "                add_button.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "                add_button.setStyleSheet(\"background-color: #3533CD; color: white;\")  # Set font color to white\n",
    "                add_button.setGeometry(480, 30, 30, 30)\n",
    "                add_button.clicked.connect(self.add_index)\n",
    "\n",
    "                exit_button = QtWidgets.QPushButton(\"\", button_frame)\n",
    "                exit_button.setIcon(QtGui.QIcon(\"exit.png\"))\n",
    "                exit_button.setIconSize(QtCore.QSize(button_size, button_size))\n",
    "                exit_button.setStyleSheet(\"background-color: transparent;\")\n",
    "                exit_button.setGeometry(button_margin + button_spacing * 5, 20, button_size, button_size)\n",
    "                #exit_button.clicked.connect(self.exit_application)\n",
    "\n",
    "                # Create the plot space\n",
    "                self.plot_space = QtWidgets.QWidget(self)\n",
    "                self.plot_space.setStyleSheet(\"background-color:#3533CD\")\n",
    "                self.plot_space.setGeometry(10, 250, window_width - 20, 400)\n",
    "\n",
    "                # Create the beat label\n",
    "                self.beat_label = QtWidgets.QLabel(self)\n",
    "                self.beat_label.setFont(QtGui.QFont(\"Arial\", 12))\n",
    "                self.beat_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "                self.beat_label.setGeometry(int((window_width -700) / 2), 660, window_width - 100, 30)\n",
    "\n",
    "                # Create the footer label\n",
    "                footer_label = QtWidgets.QLabel(\"© 2023 AWAKE Plot Viewer. All rights reserved.\", self)\n",
    "                footer_label.setFont(QtGui.QFont(\"Arial\", 10))\n",
    "                footer_label.setStyleSheet(\"background-color:#3533CD; color: white;\")  # Set font color to white\n",
    "                footer_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "                footer_label.setGeometry(10, 790, window_width - 20, 20)\n",
    "\n",
    "                plot = fig.add_subplot(111)\n",
    "                plot.plot(0, 0)\n",
    "                plot.set_xlabel('X', color='white')  # Set X-axis label color to white\n",
    "                plot.set_ylabel('Y', color='white')  # Set Y-axis label color to white\n",
    "                plot.set_title('Plot', color='white')  # Set title color to white\n",
    "\n",
    "                # Set tick color and tick label color to white\n",
    "                plot.tick_params(colors='white')\n",
    "                plot.xaxis.label.set_color('white')\n",
    "                plot.yaxis.label.set_color('white')\n",
    "\n",
    "\n",
    "                canvas = FigureCanvas(fig)\n",
    "                canvas.setGeometry(0, 0, 780, 400)\n",
    "                canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "                canvas.setParent(self.plot_space)\n",
    "\n",
    "                self.setWindowTitle(\"Plot Viewer\")\n",
    "                self.setStyleSheet(\"background-color:#3533CD;\")\n",
    "\n",
    "            def refresh(self):\n",
    "                for child in self.plot_space.children():\n",
    "                    child.deleteLater()\n",
    "                self.input_space.clear()\n",
    "                self.beat_label.setText(\"\")\n",
    "\n",
    "            def add_index(self):\n",
    "                index_text = self.input_space.text()\n",
    "                if index_text:\n",
    "                    self.index = int(index_text) + 1\n",
    "                    self.input_space.setText(str(self.index))\n",
    "\n",
    "            def subtract_index(self):\n",
    "                index_text = self.input_space.text()\n",
    "                if index_text and int(index_text) > 0:\n",
    "                    self.index = int(index_text) - 1\n",
    "                    self.input_space.setText(str(self.index))\n",
    "\n",
    "            def plot_graph(self):\n",
    "                for child in self.plot_space.children():\n",
    "                    child.deleteLater()\n",
    "\n",
    "                index = int(self.input_space.text())\n",
    "                fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "                plot = fig.add_subplot(111)\n",
    "                plot.plot(test_df.iloc[index].values)\n",
    "                plot.set_xlabel('X', color='white')  # Set X-axis label color to white\n",
    "                plot.set_ylabel('Y', color='white')  # Set Y-axis label color to white\n",
    "                plot.set_title('Plot', color='white')  # Set title color to white\n",
    "\n",
    "                # Set tick color and tick label color to white\n",
    "                plot.tick_params(colors='white')\n",
    "                plot.xaxis.label.set_color('white')\n",
    "                plot.yaxis.label.set_color('white')\n",
    "\n",
    "                # Set the color of the frame and the spines to white\n",
    "                plot.spines['top'].set_color('white')\n",
    "                plot.spines['bottom'].set_color('white')\n",
    "                plot.spines['left'].set_color('white')\n",
    "                plot.spines['right'].set_color('white')\n",
    "\n",
    "                canvas = FigureCanvas(fig)\n",
    "                canvas.setGeometry(0, 0, 780, 400)\n",
    "                canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "                canvas.setParent(self.plot_space)\n",
    "                canvas.show()\n",
    "\n",
    "\n",
    "\n",
    "            # Retrieve the array element from test_df based on the input index\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "            def save_plot(self):\n",
    "                index = int(self.input_space.text())\n",
    "\n",
    "                x_array = test_df.iloc[index].values\n",
    "                x_reshaped = x_array[:186].reshape(-1, 186, 1)\n",
    "                y_predict = model.predict(x_reshaped)\n",
    "                y_pred_inv = np.argmax(y_predict, axis=1)\n",
    "\n",
    "                if 0 in y_pred_inv:\n",
    "                    beat_type = \"Non-ectopic beats detected\"\n",
    "                elif 1 in y_pred_inv:\n",
    "                    beat_type = \"Supraventricular ectopic beats detected\"\n",
    "                elif 2 in y_pred_inv:\n",
    "                    beat_type = \"Ventricular ectopic beats detected\"\n",
    "                elif 3 in y_pred_inv:\n",
    "                    beat_type = \"Fusion Beats detected\"\n",
    "                elif 4 in y_pred_inv:\n",
    "                    beat_type = \"Unknown Beats detected\"\n",
    "                else:\n",
    "                    beat_type = \"Beat type not detected\"\n",
    "                self.beat_label.setText(beat_type)\n",
    "                self.beat_label.setAlignment(QtCore.Qt.AlignCenter)\n",
    "                self.beat_label.setStyleSheet(\"background-color: black; color: white;\")\n",
    "\n",
    "\n",
    "            def play_audio(self):\n",
    "                index = int(self.input_space.text())\n",
    "\n",
    "                if 0 <= index < len(file_list):\n",
    "                    file_name = file_list[index]\n",
    "                    file_path = os.path.join(folder_path, file_name)\n",
    "                    string_with_backslashes = file_path\n",
    "                    string_with_forwardslashes = string_with_backslashes.replace('\\\\', '/')\n",
    "                    print(string_with_forwardslashes)\n",
    "\n",
    "                    #playsound(string_with_forwardslashes, alias='my_audio_alias')\n",
    "                    pygame.mixer.init()\n",
    "                    pygame.mixer.music.load(string_with_forwardslashes)\n",
    "                    pygame.mixer.music.play()\n",
    "\n",
    "\n",
    "            def show_spectrogram(self):\n",
    "                class_number=0\n",
    "                size=70\n",
    "                min_=5\n",
    "                bins=65\n",
    "                for child in self.plot_space.children():\n",
    "                    child.deleteLater()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "                index = int(self.input_space.text())\n",
    "\n",
    "                img = test_df.iloc[20000].values\n",
    "\n",
    "\n",
    "                ###\n",
    "                img=test_df.loc[test_df[187]==class_number].values\n",
    "                img=img[:,min_:size]\n",
    "                img_flatten=img.flatten()\n",
    "\n",
    "                final1=np.arange(min_,size)\n",
    "                for i in range (img.shape[0]-1):\n",
    "                    tempo1=np.arange(min_,size)\n",
    "                    final1=np.concatenate((final1, tempo1), axis=None)\n",
    "\n",
    "                img=plt.hist(final1,img_flatten, cmap=plt.cm.jet)\n",
    "                plt.show()\n",
    "\n",
    "\n",
    "\n",
    "                \"\"\"spectrogram = librosa.feature.melspectrogram(y=img, sr=0.1, n_fft=100, hop_length=256)\n",
    "                fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "                plot = fig.add_subplot(111)\n",
    "                img = librosa.display.specshow(spectrogram,  x_axis='time', y_axis='mel',\n",
    "                                               sr=0.1, ax=plot)\"\"\"\n",
    "                fig = plt.Figure(figsize=(6, 4), dpi=100, facecolor=\"#3533CD\")\n",
    "                plot = fig.add_subplot(111)\n",
    "\n",
    "                # Set axis label color and font color to white\n",
    "                plot.set_title('Spectrogram', color='white')\n",
    "                plot.set_xlabel('Time', color='white')\n",
    "                plot.set_ylabel('Frequency', color='white')\n",
    "\n",
    "                # Set tick color and tick label color to white\n",
    "                plot.tick_params(colors='white')\n",
    "                plot.xaxis.label.set_color('white')\n",
    "                plot.yaxis.label.set_color('white')\n",
    "\n",
    "                # Set the color of the frame and the spines to white\n",
    "                plot.spines['top'].set_color('white')\n",
    "                plot.spines['bottom'].set_color('white')\n",
    "                plot.spines['left'].set_color('white')\n",
    "                plot.spines['right'].set_color('white')\n",
    "\n",
    "                canvas = FigureCanvas(img)\n",
    "                canvas.setGeometry(0, 0, 780, 400)\n",
    "                canvas.setStyleSheet(\"background-color:#3533CD;\")\n",
    "                canvas.setParent(self.plot_space)\n",
    "                canvas.show()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "             \n",
    "\n",
    "        print(2)\n",
    "        app = QtWidgets.QApplication(sys.argv)\n",
    "        viewer = PlotViewer()\n",
    "\n",
    "\n",
    "        viewer.show()\n",
    "        print(1)\n",
    "        \n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app = QApplication(sys.argv)\n",
    "    menu_window = MenuWindow()\n",
    "    menu_window.show()\n",
    "    sys.exit(app.exec_())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4ab35d9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
